- title: Brand Strategy
  content: Clearly defining who the client wants to be and then providing research-based guidance on how to approach the future.
- title: Design & Identity
  content: Using strategy to develop a unique brand that’s not only visually engaging, but also faithful to their vision.
- title: Front-End Development
  content: Building out compelling, clean, and secure sites using Jekyll and Forestry.io.
- title: Digital Marketing
  content: Promoting the clients’ brands on the ever-changing digital landscape via strategy, social media, SEO, and more.
- title: Art Direction
  content: Working with an established team to help zero in and solve a specific problem, or polish up brand guidelines.